<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default scoreboard</name>
  <uuid>fa8497b0-9ee0-490f-bc95-5ffc80cd8974</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 'ML model invocation' is in error
then
set decision to a new Scoreboard where
	the Confidence is 0,
	High risk is true,
	the Segment is "Unknown" ;	]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
