<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>machineLearningScoreboard</name>
  <uuid>86488949-3b4e-4d04-9aeb-3cc70d3a7107</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to predict( 'Input mapping' ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
